### ISSUE TITLE
missing UTM grid info!

### ISSUE THREAD

**Issue by vincentsarago** [stac-utils/stac-sentinel#2]
https://github.com/stac-utils/stac-sentinel/blob/608b495d59ab5aafc099eb35e3b07c279571dec1/stac_sentinel/sentinel.py#L46-L49

**Comment by matthewhanson** [comment]
I was confused for a minute, because this is being used by Earth-search, which does have `sentinel:utm_zone`

Turns out I'm using the develop branch:
https://github.com/stac-utils/stac-sentinel/blob/develop/stac_sentinel/sentinel.py#L44

I'll be spending some time getting this up to date in the next couple weeks, and getting the open PR merged.  Probably will make a release, but then will be integrating this into stactools.
